### ISSUE TITLE
Geopackage not displaying geometry on QGIS

### ISSUE THREAD

**Issue by ancazugo** [PatBall1/detectree2#101]
After stitching a set of predictions with the following lines of code, I create a geopackage file containing the polygons of the predictions. Still, when uploading the file in QGIS, the polygons are not present, even though they can be visualised as a geopandas data frame in Python. The attributes are present once uploaded in QGIS but cannot be seen on the map.

``` python
crowns_final = stitch_crowns(test_pred_geo_folder, 1)
crowns_final = crowns_final[crowns_final.is_valid]
crowns_final = clean_crowns(crowns_final, 0.6)
crowns_final = crowns_final[crowns_final["Confidence_score"] > 0.5]
crowns_final = crowns_final.set_geometry('geometry')
crowns_final.to_file(train_out_dir + f"test_crowns_out.gpkg")
```

`test_pred_geo_folder` and `train_out_dir` are predefined variables pointing to existing folders.

**Comment by PatBall1** [comment]
@ancazugo thanks for raising this issue. It happens because the geopackage is outputting a geopandas df without an assigned CRS. You can set this with `GeoDataFrame.set_crs`. You can also manually set it in QGIS and the output should appear with other layers. But this is something that should be automatic and is worth us implementing.
